HOST = '0.0.0.0'
PORT = 12345
BACKLOG = 5

DELIMITER = '|'

REQUEST_LIST = {
    'REQUEST_LOGIN': '0001',
    'REQUEST_SEND_MESSAGE': '0002'
}

"""第一位表示请求或回应，第二位表结果，第三四位表类型"""
RESPONSE_LIST = {
    'RESPONSE_LOGIN_SUCCESS': '1011',
    'RESPONSE_LOGIN_FAIL': '1001',
    'RESPONSE_SEND_MESSAGE_SUCCESS': '1012',
    'RESPONSE_SEND_MESSAGE_FAIL': '1002'
}